name: plastic_warriors
description: A RPG game built in Flutter. About Plastic Pollution.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  app_ui:
    path: packages/app_ui
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.6.0
  jenny: ^1.0.0

  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  bonfire: ^3.2.0
  flame_audio: ^2.1.7
  flame_splash_screen: ^0.2.0
  url_launcher: ^6.2.4
  leaderboard_repository:
    path: packages/leaderboard_repository
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  share_plus: ^7.2.1
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  flow_builder: ^0.0.9


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3
  rename: ^3.0.1 
  build_runner:
  flutter_gen_runner:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/images/emote/
    - assets/images/npc/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/bag_monster/
    - assets/images/enemy/imp/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/boss/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/
    - assets/audio/
    - assets/music/
    - assets/lang/
    - assets/lang/en.json
    - assets/lang/zh.json
    - assets/lang/ms.json

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
