class Urls {
  static const String githubRepo = 'https://github.com/';

  static const String flutterGames = 'https://flutter.dev/games';

  static const String privacyPolicy = 'https://policies.google.com/privacy';

  static const String termsOfService = 'https://policies.google.com/terms';

  static const String howWeBuilt =
      'https://bnext.my/blog/game-development/gaming-for-good-asean-peace-and-sustainability-in-the-global-gamers-challenge/';

  static const appStoreLink =
      'https://apps.apple.com/app/super-dash-flutter-game/id6473050393';

  static const playStoreLink =
      'https://play.google.com/store/apps/details?id=my.bnext.plasticwarrioes';

  static const String music1Link =
      'https://www.youtube.com/watch?v=pMMHNDxXLIg';

  static const String music2Link =
      'https://www.youtube.com/watch?v=Q6DgYoTAc0c';

  static const String kahyanLink =
      'https://www.linkedin.com/in/leong-kah-yan-9a5b49146';

  static const String louistanLink =
      'https://www.linkedin.com/in/louistan98my/';

  static const String wesleyLink = 'https://www.linkedin.com/in/wesleychong21/';

  static const String card1Link =
      'https://pay.google.com/gp/v/save/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmbHV0dGVyLXRlc3RpbmctbG91aXNAbXktZmx1dHRlci1wcm9qZWN0LTQxMzExNC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsImF1ZCI6Imdvb2dsZSIsIm9yaWdpbnMiOlsid3d3LmV4YW1wbGUuY29tIl0sInR5cCI6InNhdmV0b3dhbGxldCIsInBheWxvYWQiOnsiZ2VuZXJpY0NsYXNzZXMiOlt7ImlkIjoiMzM4ODAwMDAwMDAyMjMxNTA5Ni5teVRlc3RDbGFzczIyMiJ9XSwiZ2VuZXJpY09iamVjdHMiOlt7ImlkIjoiMzM4ODAwMDAwMDAyMjMxNTA5Ni5teVRlc3RPYmplY3RhYmNkZ2dnZyIsImNsYXNzSWQiOiIzMzg4MDAwMDAwMDIyMzE1MDk2Lm15VGVzdENsYXNzMjIyIiwic3RhdGUiOiJBQ1RJVkUiLCJoZXJvSW1hZ2UiOnsic291cmNlVXJpIjp7InVyaSI6Imh0dHBzOi8vaS5pYmIuY28vUFpKTThYRy9UaGUtd2VpZ2h0LW9mLXdhc3RlLWZsYXNoY2FyZC5wbmcifSwiY29udGVudERlc2NyaXB0aW9uIjp7ImRlZmF1bHRWYWx1ZSI6eyJsYW5ndWFnZSI6ImVuLVVTIiwidmFsdWUiOiJIZXJvIGltYWdlIGRlc2NyaXB0aW9uIn19fSwidGV4dE1vZHVsZXNEYXRhIjpbeyJoZWFkZXIiOiJQbGFzdGljIFdhcnJpb3JzISEhIiwiYm9keSI6Ikdvb2dsZSBXYWxsZXQgQ2hhbGxlbmdlIDpEIiwiaWQiOiJURVhUX01PRFVMRV9JRCJ9XSwibGlua3NNb2R1bGVEYXRhIjp7InVyaXMiOlt7InVyaSI6Imh0dHA6Ly9tYXBzLmdvb2dsZS5jb20vIiwiZGVzY3JpcHRpb24iOiJNeSBMaW5rIERlc2NyaXB0aW9uIChJbnB1dCkiLCJpZCI6IkxJTktfTU9EVUxFX1VSSV9JRCJ9LHsidXJpIjoidGVsOjY1MDU1NTU1NTUiLCJkZXNjcmlwdGlvbiI6Ik15IFRlbGVwaG9uZSBEZXNjcmlwdGlvbiAoSW5wdXQpIiwiaWQiOiJMSU5LX01PRFVMRV9URUxfSUQifV19LCJpbWFnZU1vZHVsZXNEYXRhIjpbeyJtYWluSW1hZ2UiOnsic291cmNlVXJpIjp7InVyaSI6Imh0dHBzOi8vaS5pYmIuY28vUUZRZ3E4UC9EQUxMLUUtMjAyNC0wMS0yMi0xOS0yMS0xNC1Bbi1leHRlbmRlZC1waXhlbC1hcnQtc3RyZWV0c2NhcGUtZmVhdHVyaW5nLXRyb3BpY2FsLXRyZWVzLW11bHRpcGxlLXN0b3JlLnBuZyJ9LCJjb250ZW50RGVzY3JpcHRpb24iOnsiZGVmYXVsdFZhbHVlIjp7Imxhbmd1YWdlIjoiZW4tVVMiLCJ2YWx1ZSI6IkltYWdlIG1vZHVsZSBkZXNjcmlwdGlvbiJ9fX0sImlkIjoiSU1BR0VfTU9EVUxFX0lEIn1dLCJjYXJkVGl0bGUiOnsiZGVmYXVsdFZhbHVlIjp7Imxhbmd1YWdlIjoiZW4tVVMiLCJ2YWx1ZSI6IlBMQVNUSUMgV0FSUklPUlMifX0sImhlYWRlciI6eyJkZWZhdWx0VmFsdWUiOnsibGFuZ3VhZ2UiOiJlbi1VUyIsInZhbHVlIjoiVGhlIFdlaWdodCBvZiBXYXN0ZSJ9fSwiaGV4QmFja2dyb3VuZENvbG9yIjoiIzEzYjZlMyIsImxvZ28iOnsic291cmNlVXJpIjp7InVyaSI6Imh0dHBzOi8vaS5pYmIuY28vV3RUUVI2ei9TY3JlZW5zaG90LTIwMjQtMDEtMjctYXQtMy0wMi0xMC1QTTIucG5nIn0sImNvbnRlbnREZXNjcmlwdGlvbiI6eyJkZWZhdWx0VmFsdWUiOnsibGFuZ3VhZ2UiOiJlbi1VUyIsInZhbHVlIjoiUGxhc3RpYyBXYXJyaW9ycyBMb2dvIn19fX1dfSwiaWF0IjoxNzA4OTUwODg4fQ.JenoO_2CJ_coKlj6gDzId_BK5oFS4C9mCpqyFObbkYvd-79BWY6rhCsmntcyH2wpSovftL_eyGT191jwt9VqaA4bQ5BnVAeKViLJiA6FzeLpmGKNDp2j20xmgaKm8JDB5oT3t5wRS9B3Aq4_wqx1-Zum3kRprPNnpCvZKlzw62WX1Hm6sbjqRT2OI2uDIUURiiaD-b8lXxBZScNSnl10WLp6Prs_UI82ojWuc4tocs3mmSrObJAiB7ZPdFJ9Fhueg9GlCNv5-ZUKMkmZuiuTPBggU3t2MAEC6kAf_kAGUXiZj8HYq5MaioRTXsU9kGTPYU0w-c_e0WKrqaazjiXJNg';
}
