// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuPm-MVv7WdWFsiMNFULq3yavhwjl8M4',
    appId: '1:931860057674:web:f1527b5801417b309f20b3',
    messagingSenderId: '931860057674',
    projectId: 'plastic-warriors-862da',
    authDomain: 'plastic-warriors-862da.firebaseapp.com',
    storageBucket: 'plastic-warriors-862da.appspot.com',
    measurementId: 'G-N6LTCNFDN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQzJZAVVzo5DR4sNqPWl3j-XJY1OZszto',
    appId: '1:931860057674:android:9561338a1afed0c19f20b3',
    messagingSenderId: '931860057674',
    projectId: 'plastic-warriors-862da',
    storageBucket: 'plastic-warriors-862da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgX9DYtX39zHkQl74yPDDfEIYfwLLWCk',
    appId: '1:931860057674:ios:7dd89b98195e29019f20b3',
    messagingSenderId: '931860057674',
    projectId: 'plastic-warriors-862da',
    storageBucket: 'plastic-warriors-862da.appspot.com',
    iosBundleId: 'my.bnext.plasticwarriors',
  );
}
